num1 = input("Enter First number: ")
num2 = input("Enter Second number: ")

sum = float(num1)+float(num2)
min = float(num1)-float(num2)
mul = float(num1)*float(num2)
div = float(num1)/float(num2)
mod = float(num1)%float(num2)
exp = float(num1)**float(num2)
fd = float(num1)//float(num2)

print ("Addition ",sum)
print ("Subtraction ",min)
print ("Multiplication ",mul)
print ("Division ",div)
print ("modulas ",mod)
print ("Exponentiation ",exp)
print ("floor division ",fd)
