file = open('Deepak.txt','w')
str = input('Enter text:')
file.write(str)
file = open('Deepak.txt','a')
str0 = input("Enter text to append: ")
file.write("\n"+str0)
file = open('Deepak.txt','r')
str1 =file.read()
print(str1)
file.close()
